Update PMF handler
AMReX-Combustion/PelePhysics pull request #214
Opened 2021-10-28 22:43 UTC by esclapez

- first pass at providing a straightened framework to handle PMF data and host/device locations.
 - new Testing/Exec/PMFReader tested on CPU & GPU CUDA w & w/o managed memory.

2021-10-28 23:58 UTC, drummerdoc approved these changes

2021-10-29 13:03 UTC, marchdf requested changes

2021-10-29 13:03 UTC, marchdf commented on Testing/Exec/Make.PelePhysics
> +#$(objForExecs): TPL
Is this intended?

2021-10-29 13:03 UTC, marchdf commented on Testing/Exec/PMFReader/main.cpp
> +    // -----------------------------------------------------------------------------
not a fan of these kinds of comments ;) I would be in favor of removing the `--------` lines.

2021-10-29 13:03 UTC, marchdf commented on Testing/Exec/PMFReader/main.cpp
> +   int coord = -1;
Indentation? Feed this through `clang-format`?

2021-10-29 13:03 UTC, marchdf commented on Testing/Exec/ReactEval/extern_parameters_F.H
> +
Do we need this file?

2021-10-29 13:03 UTC, marchdf commented on Utility/PMF/PMFData.H
> +        m_data_d = (DataContainer*) amrex::The_Device_Arena()->alloc(sizeof(m_data_h));
I think we should make this `The_Arena` instead of the Device_Arena. Should be done in the transport as well. I know they are the same but I think it is clearer.

2021-10-29 17:45 UTC, esclapez commented on Testing/Exec/PMFReader/main.cpp
> +    // -----------------------------------------------------------------------------
I like those, but I can remove it here

2021-10-29 17:46 UTC, esclapez commented on Testing/Exec/ReactEval/extern_parameters_F.H
> +
No, I don't think we need extern at all anymore. Ill try to remove it from the GNUmake actually.

2021-10-29 17:46 UTC, esclapez commented on Utility/PMF/PMFData.H
> +        m_data_d = (DataContainer*) amrex::The_Device_Arena()->alloc(sizeof(m_data_h));
I agree

2021-10-29 18:53 UTC, marchdf commented on Testing/Exec/PMFReader/main.cpp
> +    // -----------------------------------------------------------------------------
haha again, totally a preference thing. Keep if you want ;)

2021-11-01 18:14 UTC, marchdf approved these changes

2021-11-01 18:39 UTC, jrood-nrel approved these changes

2021-11-01 21:09 UTC, merged