WIP: Introducing CEPTR for cantera to Pele C++ mechanisms
AMReX-Combustion/PelePhysics pull request #265
Opened 2022-04-22 15:36 UTC by marchdf

I got tired of supporting Pythia and Fuego not being able to parse mechanisms.

Here is a new mechanism converter. Notable things:
- converts Cantera yaml files to mechanism.{cpp,H}
- it is easy to get a cantera yaml file: `ck2yaml --input=mechanism.inp --thermo=therm.dat --transport=tran.dat --permissive` and I will be converting all our files to yaml in the near future
- you just `poetry run convert ${PATH_TO_CANTERA_YAML_FILE}`
- no more pythia. I want a commit where both exist, so I will be removing that in a separate PR

Things left to do
- [ ] document how to setup and run
- [ ] port over QSS (mostly done but I need help checking)
- [ ] regenerate (and check!) all mechanisms to make sure that everything is ok
- [ ] convert all mechanism.inp chemkin stuff to yaml

2022-04-26 14:06 UTC, marchdf commented
Some fun stats. This PR should enable us to replace Pythia:
```
┏━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━┓
┃ Language      ┃ Files ┃     % ┃  Code ┃    % ┃ Comment ┃    % ┃
┡━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━╇━━━━━━━━━╇━━━━━━┩
│ Python        │   496 │  60.0 │ 31290 │ 52.0 │   13920 │ 23.1 │
│ C++           │    35 │   4.2 │ 13283 │ 65.8 │    3966 │ 19.6 │
│ Objective-C++ │    91 │  11.0 │  3164 │ 74.4 │      29 │  0.7 │
│ FortranFixed  │     7 │   0.8 │  2432 │ 40.1 │    3612 │ 59.6 │
│ C             │    36 │   4.4 │   851 │ 40.7 │     713 │ 34.1 │
│ TOML          │     2 │   0.2 │   551 │ 86.2 │       0 │  0.0 │
│ HTML          │     2 │   0.2 │   128 │ 56.6 │      26 │ 11.5 │
│ Makefile      │     3 │   0.4 │    44 │ 50.0 │      19 │ 21.6 │
│ markdown      │     1 │   0.1 │    20 │ 55.6 │       0 │  0.0 │
│ Singularity   │     4 │   0.5 │     6 │  6.7 │      80 │ 89.9 │
│ __unknown__   │   127 │  15.4 │     0 │  0.0 │       0 │  0.0 │
│ __duplicate__ │    13 │   1.6 │     0 │  0.0 │       0 │  0.0 │
│ __binary__    │     9 │   1.1 │     0 │  0.0 │       0 │  0.0 │
├───────────────┼───────┼───────┼───────┼──────┼─────────┼──────┤
│ Sum           │   826 │ 100.0 │ 51769 │ 55.1 │   22365 │ 23.8 │
└───────────────┴───────┴───────┴───────┴──────┴─────────┴──────┘
```

with CEPTR:
```
┏━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━┓
┃ Language         ┃ Files ┃     % ┃ Code ┃     % ┃ Comment ┃   % ┃
┡━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━┩
│ Python           │    16 │  72.7 │ 7062 │  70.4 │     548 │ 5.5 │
│ TOML             │     2 │   9.1 │  932 │  84.7 │       0 │ 0.0 │
│ reStructuredText │     1 │   4.5 │    3 │ 100.0 │       0 │ 0.0 │
│ __unknown__      │     2 │   9.1 │    0 │   0.0 │       0 │ 0.0 │
│ __empty__        │     1 │   4.5 │    0 │   0.0 │       0 │ 0.0 │
├──────────────────┼───────┼───────┼──────┼───────┼─────────┼─────┤
│ Sum              │    22 │ 100.0 │ 7997 │  71.9 │     548 │ 4.9 │
└──────────────────┴───────┴───────┴──────┴───────┴─────────┴─────┘
```

2022-04-26 15:49 UTC, drummerdoc commented
Excellent!  Happy to jettison Pythia when we're ready...it served its purpose well for years, but it's time to part ways.

2022-05-16 20:40 UTC, marchdf commented
@malihass helped me check this with ignition delay of LiDryer:
![Figure_1](https://user-images.githubusercontent.com/15038415/168678807-74e111da-eece-444d-be90-9125cbf41e95.png)


We are checking other mechanisms as well.

2022-05-18 02:47 UTC, marchdf commented
dodecane_lu:
<img width="1021" alt="Screen Shot 2022-05-17 at 8 46 25 PM" src="https://user-images.githubusercontent.com/15038415/168946662-44380aef-8980-401c-8bbc-5cfab3c5c0c1.png">

2022-05-18 02:48 UTC, marchdf commented
dodecan_lu_qss:
<img width="640" alt="Screen Shot 2022-05-17 at 8 48 02 PM" src="https://user-images.githubusercontent.com/15038415/168946843-12573b65-7afd-4316-9620-39d77ec8677f.png">

2022-05-18 20:49 UTC, jrood-nrel approved these changes

2022-05-19 17:29 UTC, marchdf commented
Any objections to merging this?

2022-05-19 17:59 UTC, merged

2022-05-19 18:01 UTC, malihass requested changes

2022-05-19 18:01 UTC, malihass commented on Support/Fuego/Mechanism/Models/Aromatic_KrNara/mechanism.yaml
> +  state: {T: 300.0, P: 1 atm}
Isn't it a bit odd to have the state of the mixture in the mechanism file ?

2022-05-19 18:01 UTC, malihass commented on Testing/Exec/CeptrTest/CanteraSimulation/homogenous-reactor.py
> +"""Run a homegenous reactor in Cantera."""
typo

2022-05-19 18:01 UTC, malihass commented on Testing/Exec/CeptrTest/PelePhysicsSimulation/utils/plotFunctions.H
> +void
I think you can clean up the `utils` folder. 
I think you only need the `initFunctions.H` and the `reactFunctions.H` Also those are in the `IgnitionDelay` test case, so maybe we can remove some redundancy here?

2022-05-19 18:25 UTC, baperry2 commented on Support/Fuego/Mechanism/Models/Aromatic_KrNara/mechanism.yaml
> +  state: {T: 300.0, P: 1 atm}
It is a bit odd but these are put in automatically by ck2yaml. I believe they just give the default conditions when creating a Solution in cantera with the mechanism. The mixture state and transport can be safely removed, but I don't think there is a need to do so.