ANSYS Fluent DPM incorporation in PeleLMeX
AMReX-Combustion/PelePhysics pull request #547
Opened 2024-11-11 05:01 UTC by SreejithNREL

Objective: Give a Fluent DPM injection file, and use that data to include the spray jet boundary in PeleLMeX.
Changes: In spray subroutines in PelePhysics. Changes in PeleLMeX will be raised as a separate PR.
Please have a look at the attached ppt for more details.
[Presentation1.pptx](https://github.com/user-attachments/files/17695360/Presentation1.pptx)
 Skipping documentation->will include those changes in the final PR.

2024-11-12 18:31 UTC, baperry2 commented
Can you pull out the mechanisms so this is only the DPM changes?

2025-05-23 16:48 UTC, baperry2 requested changes

2025-05-23 16:48 UTC, baperry2 commented on Mechanisms/posf10325/README
Remove this and other Mechanism related files from this PR.

2025-05-23 16:48 UTC, baperry2 commented on .github/workflows/dependencies/dependencies_cuda.sh
> +nvcc --version
Please try to avoid committing extraneous changes like these when submitting a PR.

2025-05-23 16:48 UTC, baperry2 commented on Docs/sphinx/Spray.rst
> +Spray data derived from ANSYS Fluent DPM solution files can also be used to inject spray particles into the fluid domain. To use this feature, initialize a spray jet (named ``jet_dpm``, say) by using
Nice documentation! Thanks for including this in the PR.

2025-05-23 16:48 UTC, baperry2 commented on Source/Eos/EOS.cpp
Remove deprecated file being added back.

2025-05-23 16:48 UTC, baperry2 commented on Source/Reactions/ReactorArkode.cpp
> +  amrex::Print() << "\nFinal Statistics: " << "(thread:" << omp_get_thread_num()
avoid formatting change to otherwise unchanged file

2025-05-23 16:48 UTC, baperry2 commented on Source/Spray/SprayInjection.H
> +    amrex::Print() << "Warning! Spray jet " << spray_jet->jet_name()
Try to wrap terminal output with `if (m_verbose > 0) {}` for classes that have a verbosity parameter so users can turn off diagnostic output if it is undesired.

2025-05-23 16:48 UTC, baperry2 commented on Source/Spray/SprayJet.cpp
> +    if (is_dpm_periodic) {
What's going on here? It looks like this conditional isn't doing anything due to the commented out code?

2025-05-31 20:12 UTC, SreejithNREL commented on Source/Reactions/ReactorArkode.cpp
> +  amrex::Print() << "\nFinal Statistics: " << "(thread:" << omp_get_thread_num()
Removed the formatting. Thanks for pointing that out.

2025-05-31 20:13 UTC, SreejithNREL commented on Source/Spray/SprayInjection.H
> +    amrex::Print() << "Warning! Spray jet " << spray_jet->jet_name()
Included the verbosity check now.

2025-05-31 20:13 UTC, SreejithNREL commented on Source/Eos/EOS.cpp
Removed file.

2025-05-31 20:14 UTC, SreejithNREL commented on .github/workflows/dependencies/dependencies_cuda.sh
> +nvcc --version
Removed the newline.

2025-05-31 20:14 UTC, SreejithNREL commented on Mechanisms/posf10325/README
Removed the mechanism files

2025-06-02 04:56 UTC, SreejithNREL commented on Source/Spray/SprayJet.cpp
> +    if (is_dpm_periodic) {
Removed the commented line which was used initially for debugging purposes

2025-06-02 17:58 UTC, baperry2 commented
I think this should be good to go now, running some checks on this with PeleC and PeleLMeX and will merge assuming those complete successfully.

2025-06-03 16:28 UTC, baperry2 approved these changes

2025-06-03 16:28 UTC, merged